---
  swagger: "2.0"
  info:
    title: "Scala Mock API"
    description: "API pour tester les appels REST"
  consumes:
    - application/json
  produces:
    - application/json
  securityDefinitions:
    BasicAuth:
      type: basic
    Bearer:
      type: apiKey
      name: Authorization
      in: header